services:
  php:
    image: webdevops/php-apache:7.4
    ports: 
      - "80:80"
      - "443:443"
    working_dir: /app
    volumes:
      - ../html:/app
    environment:
      PHP_DATE_TIMEZONE: Europe/Paris
      PHP_DISPLAY_ERRORS: 1
      DB_HOST: mariadb
      DB_USER: myUser
      DB_PASSWORD: Secr3t
      DB_NAME: name_of_the_database

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ../mariadb-data/:/var/lib/mysql/
    environment:
      MARIADB_DATABASE: name_of_the_database
      MARIADB_USER: myUser
      MARIADB_PASSWORD: Secr3t
      MARIADB_ROOT_PASSWORD: R0oT_Secr3t
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: myUser
      PMA_PASSWORD: Secr3t
